title: Shreya Agarwal # your name (or website title) here
logo: "/images/logo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm a Data Consultant with over 2.5 years experience in
  delivering data-driven social sector projects. Loves to 
  experiment with data, is curious to learn about the story
  behind the numbers/text.
  
  Also, holds over five years experience in
  news production, stock markets coverage, and equity research.
  <br><br>
  
  <a href="https://www.linkedin.com/in/shreya2105/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
